"""Transcript segment models.

Contains the atomic units of transcript data:
- words
- segments
- decoder metadata
- pipeline metadata
"""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class RawDecoderOutput(BaseModel):
    """
    Raw metadata returned by the transcription backend.

    This intentionally remains flexible because different
    transcription engines expose different information.

    FasterWhisper examples:
    - avg_logprob
    - compression_ratio
    - no_speech_prob
    - temperature
    """

    model_config = ConfigDict(extra="allow")

    data: dict[str, Any] = Field(default_factory=dict)


class PipelineSegmentMetadata(BaseModel):
    """
    Metadata generated by Dossier after transcription.

    This is information discovered by later pipeline stages,
    not produced by the ASR model.
    """

    suspicious: bool = False
    suspicion_reasons: list[str] = Field(default_factory=list)
    normalized: bool = False
    overlap_candidate: bool = False
    merge_weight: float | None = None


class TranscriptWord(BaseModel):
    """Word-level timing information."""

    start: float
    end: float

    word: str

    probability: float | None = None


class TranscriptSegment(BaseModel):
    """
    A single transcript segment.

    Represents a piece of speech produced by the decoder.

    Contains:
    - transcript text
    - timing
    - decoder metadata
    - Dossier processing metadata
    - provenance
    """

    start: float
    end: float

    text: str

    words: list[TranscriptWord] = Field(default_factory=list)
    raw_decoder_output: RawDecoderOutput = Field(default_factory=RawDecoderOutput)
    pipeline: PipelineSegmentMetadata = Field(default_factory=PipelineSegmentMetadata)

    # Provenance

    track_id: str
    chunk_id: str
    chunk_index: int
    transcription_id: str

    @property
    def duration(self) -> float:
        """Duration of the segment in seconds."""
        return self.end - self.start

    @property
    def start_time(self) -> float:
        """Start time of the segment in seconds."""
        return self.start

    @property
    def end_time(self) -> float:
        """End time of the segment in seconds."""
        return self.end
